DECLARE
   v_table_exists NUMBER;
BEGIN
   SELECT COUNT(*)
   INTO v_table_exists
   FROM all_tables
   WHERE table_name = 'DWH_DEMO_TABLE';

   IF v_table_exists = 0 THEN
      EXECUTE IMMEDIATE 'CREATE TABLE DWH_DEMO_TABLE
   (ID NUMBER GENERATED ALWAYS AS IDENTITY,
   BUSINESS_OBJECT VARCHAR2(30) NOT NULL,
   LN_ACCOUNT VARCHAR2(30),
   CREATION_DATE TIMESTAMP (6), 
   CREATED_BY VARCHAR2(25), 
   LAST_UPDATE_DATE TIMESTAMP (6), 
   LAST_UPDATED_BY VARCHAR2(25),
   NEW_COLUMN NUMBER
    )';
   END IF;
END;
/