DECLARE
   v_table_exists NUMBER;
BEGIN
   SELECT COUNT(*)
   INTO v_table_exists
   FROM all_tables
   WHERE table_name = 'ENS_SEGMENT_HIERARCHY_UPLOADS'
   AND owner = 'XX_INTEGRATION_DEV';

   IF v_table_exists = 0 THEN
      EXECUTE IMMEDIATE 'CREATE TABLE XX_INTEGRATION_DEV.ENS_SEGMENT_HIERARCHY_UPLOADS 
			   (ID NUMBER GENERATED ALWAYS AS IDENTITY,
			   MSG_ID RAW(32),
			   TREE_VERSION_NAME VARCHAR2(80),
			   UPLOAD_START DATE,
			   STATUS VARCHAR2(15),
			   STATUS_MSG VARCHAR2(4000),
				CREATION_DATE DATE,
				CREATED_BY VARCHAR2(150),
				LAST_UPDATE_DATE DATE,
				LAST_UPDATED_BY VARCHAR2(150)
				ERP_REQUEST_ID NUMBER, 
				ERP_REQUEST_STATUS VARCHAR2(15), 
				WF_INSTANCE_ID NUMBER,
				UCM_DOCUMENT_ID NUMBER
				)';
   END IF;
END;
/