DECLARE
   v_table_exists NUMBER;
BEGIN
   SELECT COUNT(*)
   INTO v_table_exists
   FROM all_tables
   WHERE table_name = 'AR_CALLBACK_MSG'
   AND owner = 'XX_INTEGRATION_DEV';

   IF v_table_exists = 0 THEN
      EXECUTE IMMEDIATE 'CREATE TABLE XX_INTEGRATION_DEV.AR_CALLBACK_MSG 
			   (	ID NUMBER GENERATED ALWAYS AS IDENTITY, 
					MESSAGE_DATA CLOB COLLATE USING_NLS_COMP, 
					JSON_CONTENT CLOB COLLATE USING_NLS_COMP, 
					STATUS VARCHAR2(15 BYTE) COLLATE USING_NLS_COMP, 
					CREATION_DATE DATE, 
					LAST_UPDATE_DATE DATE, 
					ERP_REQUEST_ID NUMBER, 
					ERP_REQUEST_STATUS VARCHAR2(15 BYTE) COLLATE USING_NLS_COMP, 
					WF_INSTANCE_ID NUMBER, 
					ORIGINAL_MSG_ID RAW(32)
				)';
   END IF;
END;
/