DECLARE
   v_table_exists NUMBER;
BEGIN
   SELECT COUNT(*)
   INTO v_table_exists
   FROM all_tables
   WHERE table_name = 'RA_INTERFACE_DISTRIBUTIONS_ALL'
   AND owner = 'XX_INTEGRATION_DEV';

   IF v_table_exists = 0 THEN
      EXECUTE IMMEDIATE 'CREATE TABLE RA_INTERFACE_DISTRIBUTIONS_ALL(
                       X_MSG_ID RAW(32),
                       X_APEX_STATUS VARCHAR2(30),
                       X_APEX_MESSAGE VARCHAR2(4000),
                       X_CREATION_DATE date,
                       X_LAST_UPDATE_DATE date,
                       ORG_ID NUMBER (18),
                       ACCOUNT_CLASS VARCHAR2(20),
                       AMOUNT NUMBER,
                       PERCENT NUMBER,
                       ACCTD_AMOUNT NUMBER,
                       INTERFACE_LINE_CONTEXT VARCHAR2(30),
                       INTERFACE_LINE_ATTRIBUTE1 VARCHAR2(30),
                       INTERFACE_LINE_ATTRIBUTE2 VARCHAR2(30),
                       INTERFACE_LINE_ATTRIBUTE3 VARCHAR2(30),
                       INTERFACE_LINE_ATTRIBUTE4 VARCHAR2(30),
                       INTERFACE_LINE_ATTRIBUTE5 VARCHAR2(30),
                       INTERFACE_LINE_ATTRIBUTE6 VARCHAR2(30),
                       INTERFACE_LINE_ATTRIBUTE7 VARCHAR2(30),
                       INTERFACE_LINE_ATTRIBUTE8 VARCHAR2(30),
                       INTERFACE_LINE_ATTRIBUTE9 VARCHAR2(30),
                       INTERFACE_LINE_ATTRIBUTE10 VARCHAR2(30),
                       INTERFACE_LINE_ATTRIBUTE11 VARCHAR2(30),
                       INTERFACE_LINE_ATTRIBUTE12 VARCHAR2(30),
                       INTERFACE_LINE_ATTRIBUTE13 VARCHAR2(30),
                       INTERFACE_LINE_ATTRIBUTE14 VARCHAR2(30),
                       INTERFACE_LINE_ATTRIBUTE15 VARCHAR2(30),
                       SEGMENT1 VARCHAR2(25),
                       SEGMENT2 VARCHAR2(25),
                       SEGMENT3 VARCHAR2(25),
                       SEGMENT4 VARCHAR2(25),
                       SEGMENT5 VARCHAR2(25),
                       SEGMENT6 VARCHAR2(25),
                       SEGMENT7 VARCHAR2(25),
                       SEGMENT8 VARCHAR2(25),
                       SEGMENT9 VARCHAR2(25),
                       SEGMENT10 VARCHAR2(25),
                       SEGMENT11 VARCHAR2(25),
                       SEGMENT12 VARCHAR2(25),
                       SEGMENT13 VARCHAR2(25),
                       SEGMENT14 VARCHAR2(25),
                       SEGMENT15 VARCHAR2(25),
                       SEGMENT16 VARCHAR2(25),
                       SEGMENT17 VARCHAR2(25),
                       SEGMENT18 VARCHAR2(25),
                       SEGMENT19 VARCHAR2(25),
                       SEGMENT20 VARCHAR2(25),
                       SEGMENT21 VARCHAR2(25),
                       SEGMENT22 VARCHAR2(25),
                       SEGMENT23 VARCHAR2(25),
                       SEGMENT24 VARCHAR2(25),
                       SEGMENT25 VARCHAR2(25),
                       SEGMENT26 VARCHAR2(25),
                       SEGMENT27 VARCHAR2(25),
                       SEGMENT28 VARCHAR2(25),
                       SEGMENT29 VARCHAR2(25),
                       SEGMENT30 VARCHAR2(25),
                       COMMENTS VARCHAR2(240),
                       INTERIM_TAX_SEGMENT1 VARCHAR2(25),
                       INTERIM_TAX_SEGMENT2 VARCHAR2(25),
                       INTERIM_TAX_SEGMENT3 VARCHAR2(25),
                       INTERIM_TAX_SEGMENT4 VARCHAR2(25),
                       INTERIM_TAX_SEGMENT5 VARCHAR2(25),
                       INTERIM_TAX_SEGMENT6 VARCHAR2(25),
                       INTERIM_TAX_SEGMENT7 VARCHAR2(25),
                       INTERIM_TAX_SEGMENT8 VARCHAR2(25),
                       INTERIM_TAX_SEGMENT9 VARCHAR2(25),
                       INTERIM_TAX_SEGMENT10 VARCHAR2(25),
                       INTERIM_TAX_SEGMENT11 VARCHAR2(25),
                       INTERIM_TAX_SEGMENT12 VARCHAR2(25),
                       INTERIM_TAX_SEGMENT13 VARCHAR2(25),
                       INTERIM_TAX_SEGMENT14 VARCHAR2(25),
                       INTERIM_TAX_SEGMENT15 VARCHAR2(25),
                       INTERIM_TAX_SEGMENT16 VARCHAR2(25),
                       INTERIM_TAX_SEGMENT17 VARCHAR2(25),
                       INTERIM_TAX_SEGMENT18 VARCHAR2(25),
                       INTERIM_TAX_SEGMENT19 VARCHAR2(25),
                       INTERIM_TAX_SEGMENT20 VARCHAR2(25),
                       INTERIM_TAX_SEGMENT21 VARCHAR2(25),
                       INTERIM_TAX_SEGMENT22 VARCHAR2(25),
                       INTERIM_TAX_SEGMENT23 VARCHAR2(25),
                       INTERIM_TAX_SEGMENT24 VARCHAR2(25),
                       INTERIM_TAX_SEGMENT25 VARCHAR2(25),
                       INTERIM_TAX_SEGMENT26 VARCHAR2(25),
                       INTERIM_TAX_SEGMENT27 VARCHAR2(25),
                       INTERIM_TAX_SEGMENT28 VARCHAR2(25),
                       INTERIM_TAX_SEGMENT29 VARCHAR2(25),
                       INTERIM_TAX_SEGMENT30 VARCHAR2(25),
                       ATTRIBUTE_CATEGORY VARCHAR2(25),
                       ATTRIBUTE1 VARCHAR2(150),
                       ATTRIBUTE2 VARCHAR2(150),
                       ATTRIBUTE3 VARCHAR2(150),
                       ATTRIBUTE4 VARCHAR2(150),
                       ATTRIBUTE5 VARCHAR2(150),
                       ATTRIBUTE6 VARCHAR2(150),
                       ATTRIBUTE7 VARCHAR2(150),
                       ATTRIBUTE8 VARCHAR2(150),
                       ATTRIBUTE9 VARCHAR2(150),
                       ATTRIBUTE10 VARCHAR2(150),
                       ATTRIBUTE11 VARCHAR2(150),
                       ATTRIBUTE12 VARCHAR2(150),
                       ATTRIBUTE13 VARCHAR2(150),
                       ATTRIBUTE14 VARCHAR2(150),
                       ATTRIBUTE15 VARCHAR2(150),
                       BU_NAME VARCHAR2 (240))';
   END IF;
END;
/