DECLARE
   v_table_exists NUMBER;
BEGIN
   SELECT COUNT(*)
   INTO v_table_exists
   FROM all_tables
   WHERE table_name = 'MAP_SEG5_ACTIVITY'
   AND owner = 'XX_INTEGRATION_DEV';

   IF v_table_exists = 0 THEN
      EXECUTE IMMEDIATE 'CREATE TABLE "MAP_SEG5_ACTIVITY" 
    ("LN_INSTANCE" VARCHAR2(10), 
   "KDA_IDENTIFIER" VARCHAR2(25), 
   "ORAFIN_VALUE" VARCHAR2(25), 
   "LN_VALUE" VARCHAR2(25), 
   "ENABLED" VARCHAR2(1),
   "CREATION_DATE" TIMESTAMP (6), 
   "CREATED_BY" VARCHAR2(25), 
   "LAST_UPDATE_DATE" TIMESTAMP (6), 
   "LAST_UPDATED_BY" VARCHAR2(25)
   ) ;
            )';
   END IF;
END;
/
