CREATE OR REPLACE EDITIONABLE TRIGGER "XX_INTEGRATION_DEV"."DBO_CALLBACK_MSG_BIU" 
BEFORE INSERT OR UPDATE ON DBO_CALLBACK_MSG
FOR EACH ROW
BEGIN
    IF INSERTING THEN
      :NEW.CREATED_BY := nvl(sys_context('APEX$SESSION','APP_USER'),user);
      :NEW.CREATED_DATE := SYSDATE;
	  
    END IF;
    :NEW.CHANGED_BY := nvl(sys_context('APEX$SESSION','APP_USER'),user);
    :NEW.CHANGED_DATE := SYSDATE;
END;